/*
 * @author Pedro F. Toledo <pedrotoledocorrea@gmail.com>
 * @version 1.0
 * Generated by ConsolidatedDocumentation v1.0.xlsm
 * TimeStamp: 2015-04-06 00:19:18
 */

#include <vector>
#include <sstream>
#include <fstream>
using namespace std;
#include "enum.h"
#include "define.h"
#include "Tools.h"
#include "HashEntry.h"
#include "HashTable.h"
#include "LogManager.h"
#include "SettingsManager.h"
#include "Globals.h"
#include "InterpreterManager.h"

void InterpreterManager::InitializeInterpreter()
{
  // Variable Management
  Commands.QuickPutEntry_function(string(LABEL_VARIABLE_MANAGEMENT) + string(VARMAN_SET), (void*) InterpreterManager::VarmanCall_SET);
  Commands.QuickPutEntry_function(string(LABEL_VARIABLE_MANAGEMENT) + string(VARMAN_PRINT), (void*) InterpreterManager::VarmanCall_PRINT);
  // Run Commands
  Commands.QuickPutEntry_function(string(LABEL_RUN_SIMULATION) + string(RUNSIM_SS_INITIALIZE), (void*) InterpreterManager::RunsimCall);
  Commands.QuickPutEntry_function(string(LABEL_RUN_SIMULATION) + string(RUNSIM_SS_ADD_V1_DIFFUSION), (void*) InterpreterManager::RunsimCall);
  Commands.QuickPutEntry_function(string(LABEL_RUN_SIMULATION) + string(RUNSIM_SS_SIMULATE), (void*) InterpreterManager::RunsimCall);
  // Reporting Commands
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(REPORT_SS_PRINT_V1_ACTIVATION), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(REPORT_SS_PRINT_V1_ACTIVATION_HORIZONTAL), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(REPORT_SS_PRINT_V1_EXTERNAL_EXCITATION), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(REPORT_SS_PRINT_MT_ACTIVATION), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(REPORT_SS_PRINT_MT_ACTIVATION_HORIZONTAL), (void*) InterpreterManager::ReportCall);
  // I/O Interaction Commands
  Commands.QuickPutEntry_function(string(LABEL_IO_INTERACTIONS) + string(RESCUE_NPROC), (void*) InterpreterManager::RescueCall_NPROC);
}
