/*
 * @author Pedro F. Toledo <pedrotoledocorrea@gmail.com>
 * @version 1.0
 * Generated by ConsolidatedDocumentation v1.0.xlsm
 * TimeStamp: 2015-03-25 16:26:02
 */

#include <vector>
#include <sstream>
#include <fstream>
using namespace std;
#include "enum.h"
#include "define.h"
#include "Tools.h"
#include "HashEntry.h"
#include "HashTable.h"
#include "LogManager.h"
#include "SettingsManager.h"
#include "Globals.h"
#include "InterpreterManager.h"

void InterpreterManager::InitializeInterpreter()
{
  // Environment Settings
  Commands.QuickPutEntry_function(string(LABEL_ENVIRONMENT_SETTINGS) + string(), (void*) InterpreterManager::SetenvCall);
  // Simulator Settings
  Commands.QuickPutEntry_function(string(LABEL_SIMULATOR_SETTINGS) + string(), (void*) InterpreterManager::SetsimCall);
  // Run Commands
  Commands.QuickPutEntry_function(string(LABEL_RUN_SIMULATION) + string(SS_INITIALIZE), (void*) InterpreterManager::RunsimCall);
  Commands.QuickPutEntry_function(string(LABEL_RUN_SIMULATION) + string(SS_ADD_V1_DIFFUSION), (void*) InterpreterManager::RunsimCall);
  Commands.QuickPutEntry_function(string(LABEL_RUN_SIMULATION) + string(SS_SIMULATE), (void*) InterpreterManager::RunsimCall);
  // Reporting Commands
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(PRINT_ENV), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(PRINT_SIM), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(SS_PRINT_V1_ACTIVATION), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(SS_PRINT_V1_ACTIVATION_HORIZONTAL), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(SS_PRINT_V1_EXTERNAL_EXCITATION), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(SS_PRINT_MT_ACTIVATION), (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function(string(LABEL_REPORTING) + string(SS_PRINT_MT_ACTIVATION_HORIZONTAL), (void*) InterpreterManager::ReportCall);
  // I/O Interaction Commands
  Commands.QuickPutEntry_function(string(LABEL_IO_INTERACTIONS) + string(NPROC), (void*) InterpreterManager::RescueCall_NPROC);
}
