/*
 * @author Pedro F. Toledo <pedrotoledocorrea@gmail.com>
 * @version 1.0
 * Generated by ConsolidatedDocumentation v1.0.xlsm
 * TimeStamp: 2015-07-14 04:31:08
 */

//#include <vector>
//#include <sstream>
//#include <fstream>
//using namespace std;
#include "enum.h"
//#include "define.h"
//#include "Tools.h"
//#include "HashEntry.h"
//#include "HashTable.h"
//#include "LogManager.h"
//#include "SettingsManager.h"
//#include "Globals.h"
#include "InterpreterManager.h"
#include "NeuronmentCommand.h"

ReturnType InterpreterManager::InitializeInterpreter()
{
  Commands.PutEntryQuick("report_test", (void*) report_test);
  // I/O Interaction Commands
  Commands.PutEntryQuick("rescue_nproc", (void*) rescue_nproc);
  return ReturnSuccess;
}
