/*
 * @author Pedro F. Toledo <pedrotoledocorrea@gmail.com>
 * @version 1.0
 * Generated by ConsolidatedDocumentation v1.0.xlsm
 * TimeStamp: 2015-05-06 16:51:44
 */

#include <vector>
#include <sstream>
#include <fstream>
using namespace std;
#include "enum.h"
#include "define.h"
#include "Tools.h"
#include "HashEntry.h"
#include "HashTable.h"
#include "LogManager.h"
#include "SettingsManager.h"
#include "Globals.h"
#include "InterpreterManager.h"

void InterpreterManager::InitializeInterpreter()
{
  Commands.QuickPutEntry_function("varmanset", (void*) InterpreterManager::VarmanCall_SET);
  Commands.QuickPutEntry_function("varmanprint", (void*) InterpreterManager::VarmanCall_PRINT);
  // Run Commands
  Commands.QuickPutEntry_function("runsimss_initialize", (void*) InterpreterManager::RunsimCall);
  Commands.QuickPutEntry_function("runsimss_add_V1_diffusion", (void*) InterpreterManager::RunsimCall);
  Commands.QuickPutEntry_function("runsimss_simulate", (void*) InterpreterManager::RunsimCall);
  // Reporting Commands
  Commands.QuickPutEntry_function("reportss_print_V1_activation", (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function("reportss_print_V1_activation_horizontal", (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function("reportss_print_V1_external_excitation", (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function("reportss_print_MT_activation", (void*) InterpreterManager::ReportCall);
  Commands.QuickPutEntry_function("reportss_print_MT_activation_horizontal", (void*) InterpreterManager::ReportCall);
  // I/O Interaction Commands
  Commands.QuickPutEntry_function("rescuenproc", (void*) InterpreterManager::RescueCall_NPROC);
  Commands.QuickPutEntry_function("rescuereturn", (void*) InterpreterManager::RescueCall_RETURN);
}
