/*
 * @author Pedro F. Toledo <pedrotoledocorrea@gmail.com>
 * @version 1.0
 * Generated by ConsolidatedDocumentation v1.0.xlsm
 * TimeStamp: 2015-07-29 13:48:56
 */

//#include <vector>
//#include <string>
//#include <fstream>
//using namespace std;
#include "enum.h"
//#include "define.h"
//#include "Tools.h"
//#include "HashEntry.h"
//#include "HashTable.h"
//#include "Globals.h"
//#include "main.h"
#include "VariableManager.h"

ReturnType VariableManager::InitializeVariables()
{
  // Environment Variables
  Variables.SetSettingFromString(HIDE_END, "bool", 1);
  Variables.SetSettingFromString(MAX_NPROC_NESTING, "int", 1);
  Variables.SetSettingFromString(SHOW_ELAPSED_TIME, "bool", 1);
  // V1 Variables
  for (int i = 0; i < V1_MAX_NEURONS; i++) {    Variables.SetSetting(string("SIM:") + V1_LABEL + string("'") + IIntToString(i), double, 8);  }
  Variables.SetSettingFromString(V1_FIRST_CALCULATION, "string", 1);
  Variables.SetSettingFromString(V1_ACTIVATION_METHOD, "string", 1);
  Variables.SetSettingFromString(V1_DACTIVATION_METHOD, "string", 1);
  Variables.SetSettingFromString(V1_EXTERNAL_EXCITATION_METHOD, "string", 1);
  // V1 Activation Methods
  // V1_A001 Method Parameters
  Variables.SetSettingFromString(V1_A001_NL_MAX, "double", 1);
  Variables.SetSettingFromString(V1_A001_NL_A, "double", 1);
  Variables.SetSettingFromString(V1_A001_NL_B, "double", 1);
  // V1 Derivate Activation Methods
  // V1_D001 Method Parameters
  Variables.SetSettingFromString(V1_D001_CONDUCTANCE_LEAK, "double", 1);
  Variables.SetSettingFromString(V1_D001_EXCITATORY_FACTOR, "double", 1);
  Variables.SetSettingFromString(V1_D001_INHIBITION_FACTOR, "double", 1);
  Variables.SetSettingFromString(V1_D001_WEIGHT_FACTOR, "double", 1);
  // V1 External Excitation Method
  // V1_F001 Method Parameters
  Variables.SetSettingFromString(V1_F001_A, "double", 1);
  Variables.SetSettingFromString(V1_F001_B, "double", 1);
  Variables.SetSettingFromString(V1_F001_ORIENTATION, "double", 1);
  Variables.SetSettingFromString(V1_F001_SPATIAL_FREQUENCY, "double", 1);
  Variables.SetSettingFromString(V1_F001_TEMPORAL_FREQUENCY, "double", 1);
  Variables.SetSettingFromString(V1_F001_MAGNITUDE, "double", 1);
  Variables.SetSettingFromString(V1_F001_PHASE, "int", 1);
  // MT Variables
  for (int i = 0; i < MT_MAX_NEURONS; i++) {    Variables.SetSetting(string("SIM:") + MT_LABEL + string("'") + IIntToString(i), double, 6);  }
  Variables.SetSettingFromString(MT_FIRST_CALCULATION, "string", 1);
  Variables.SetSettingFromString(MT_ACTIVATION_METHOD, "string", 1);
  Variables.SetSettingFromString(MT_DACTIVATION_METHOD, "string", 1);
  // MT Activation Methods
  // MT_A001 Parameters
  // MT Derivate Activation Methods
  // MT_D001 Parameters
  // Linking Variables
  // V1V1 Linking Methods
  for (int i = 0; i < V1_MAX_NEURONS; i++) {    for (int j = 0; j < V1_MAX_NEURONS; j++) {      Variables.SetSetting(string("SIM:") + V1_LABEL + string("'") + IIntToString(i) + ":" + V1_LABEL + string("'") + IIntToString(j), double, 1);    }  }
  Variables.SetSettingFromString(V1V1_CONNECTION_METHOD, "string", 1);
  // V1V1_L001 Link Parameters
  Variables.SetSettingFromString(V1V1_L001_BASE_WEIGHT_SOURCE, "string", 1);
  Variables.SetSettingFromString(V1V1_L001_DEFAULT_WEIGHT, "double", 1);
  // V1MT Linking Methods
  Variables.SetSettingFromString(V1MT_CONNECTION_METHOD, "string", 1);
  // V1MT_L001 Link Parameters
  Variables.SetSettingFromString(V1MT_L001_APERTURE, "double", 1);
  Variables.SetSettingFromString(V1MT_L001_AMPLIFICATION, "double", 1);
  Variables.SetSettingFromString(V1MT_L001_SIGMA, "double", 1);
  Variables.SetSettingFromString(V1MT_L001_MODULATION, "double", 1);
  // Simulator Variables
  Variables.SetSettingFromString(SIMULATOR_TIME_STEP, "double", 1);
}
